# Generated by Django 4.2.2 on 2023-07-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsapp', '0002_alter_fieldstaff_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldstaff',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
