# Generated by Django 4.2.2 on 2023-07-05 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0005_alter_company_company_alter_company_ph_no'),
        ('fsapp', '0005_remove_fieldstaff_fieldstaff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldstaff',
            name='name',
        ),
        migrations.AddField(
            model_name='fieldstaff',
            name='fieldstaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capp.company'),
        ),
    ]
