# Generated by Django 4.2.2 on 2023-07-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsapp', '0006_remove_fieldstaff_name_fieldstaff_fieldstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldstaff',
            name='fieldstaff',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
