# Generated by Django 4.2.2 on 2023-07-05 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0005_alter_company_company_alter_company_ph_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fsapp', '0007_alter_fieldstaff_fieldstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldstaff',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capp.company'),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='fieldstaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
