# Generated by Django 4.2.2 on 2023-07-06 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fsapp', '0008_fieldstaff_name_alter_fieldstaff_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldstaff',
            name='fieldstaff',
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
