# Generated by Django 4.2.2 on 2023-07-09 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0005_alter_company_company_alter_company_ph_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fsapp', '0009_remove_fieldstaff_fieldstaff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldstaff',
            name='name',
        ),
        migrations.AddField(
            model_name='fieldstaff',
            name='fieldstaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capp.company'),
        ),
    ]
