# Generated by Django 4.2.2 on 2023-07-09 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0031_alter_dealer_dealer'),
        ('capp', '0005_alter_company_company_alter_company_ph_no'),
        ('fsapp', '0010_remove_fieldstaff_name_fieldstaff_fieldstaff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldstaff',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldstaffs', to='capp.company'),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldstaffs', to='dapp.dealer'),
        ),
    ]
