# Generated by Django 4.2.2 on 2023-07-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0031_alter_dealer_dealer'),
        ('capp', '0005_alter_company_company_alter_company_ph_no'),
        ('fsapp', '0011_alter_fieldstaff_company_alter_fieldstaff_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldstaff',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capp.company'),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.dealer'),
        ),
    ]
