# Generated by Django 4.2.3 on 2023-07-15 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0036_remove_dealer_address_remove_dealer_nationality_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fsapp', '0013_alter_fieldstaff_company_alter_fieldstaff_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldstaff',
            name='city',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldstaffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldstaffs', to='dapp.dealer'),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='email_id',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='ph_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='state',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
