# Generated by Django 4.2.3 on 2023-07-20 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0037_remove_dealer_ph_no_dealer_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fsapp', '0014_alter_fieldstaff_city_alter_fieldstaff_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldstaff',
            name='ph_no',
        ),
        migrations.AddField(
            model_name='fieldstaff',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fieldstaff',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fieldstaff',
            name='phone_no',
            field=models.CharField(blank=True, default='+977-', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fieldstaffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='dealer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fieldstaffs', to='dapp.dealer'),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='fieldstaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
