# Generated by Django 4.2.3 on 2023-07-25 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dapp', '0039_alter_dealer_company'),
        ('fsapp', '0016_remove_fieldstaff_phone_no_fieldstaff_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldstaff',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_fieldstaffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dealer_fieldstaffs', to='dapp.dealer'),
        ),
    ]
