# Generated by Django 4.2.3 on 2023-07-26 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fsapp', '0017_alter_fieldstaff_company_alter_fieldstaff_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldstaff',
            name='fieldstaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fieldstaff_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
