# Generated by Django 4.2.3 on 2023-07-26 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0039_alter_dealer_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fsapp', '0018_alter_fieldstaff_fieldstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldstaff',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_fieldstaf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dealer_fieldstaff', to='dapp.dealer'),
        ),
    ]
