# Generated by Django 4.2.2 on 2023-07-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_Group_Dealer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_Group_FieldStaff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_Group_Retailer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_Group_company',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_Company',
            field=models.BooleanField(default=False, verbose_name='Is Company'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_Dealer',
            field=models.BooleanField(default=False, verbose_name='Is Dealer'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_FieldStaff',
            field=models.BooleanField(default=False, verbose_name='Is FieldStaff'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_Retailer',
            field=models.BooleanField(default=False, verbose_name='Is Retailer'),
        ),
    ]
