# Generated by Django 4.2.3 on 2023-07-27 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_added_by_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_no',
        ),
    ]
