# Generated by Django 4.2.2 on 2023-07-02 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0002_remove_company_name_company_company'),
        ('dapp', '0002_alter_dealer_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='name',
        ),
        migrations.AddField(
            model_name='dealer',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capp.company'),
        ),
    ]
