# Generated by Django 4.2.2 on 2023-07-02 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dapp', '0004_alter_dealer_company_alter_dealer_dealer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='dealer',
        ),
        migrations.AddField(
            model_name='dealer',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
