# Generated by Django 4.2.2 on 2023-07-04 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0004_alter_company_ph_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dapp', '0008_alter_dealer_company_alter_dealer_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capp.company'),
        ),
    ]
