# Generated by Django 4.2.2 on 2023-07-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0009_alter_dealer_company_alter_dealer_dealer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='dealer',
        ),
        migrations.AddField(
            model_name='dealer',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
