# Generated by Django 4.2.2 on 2023-07-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0005_alter_company_company_alter_company_ph_no'),
        ('dapp', '0010_remove_dealer_dealer_dealer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='name',
        ),
        migrations.AddField(
            model_name='dealer',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capp.company'),
        ),
    ]
