# Generated by Django 4.2.2 on 2023-07-05 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0005_alter_company_company_alter_company_ph_no'),
        ('dapp', '0016_alter_dealer_company_alter_dealer_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_set', to='capp.company'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_set', to='capp.company'),
        ),
    ]
