# Generated by Django 4.2.2 on 2023-07-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0017_alter_dealer_company_alter_dealer_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='dealer',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
