# Generated by Django 4.2.2 on 2023-07-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0020_alter_dealer_company_alter_dealer_dealer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='dealer',
        ),
    ]
