# Generated by Django 4.2.2 on 2023-07-07 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0005_alter_company_company_alter_company_ph_no'),
        ('dapp', '0021_remove_dealer_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealers', to='capp.company'),
        ),
    ]
