# Generated by Django 4.2.2 on 2023-07-09 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0005_alter_company_company_alter_company_ph_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dapp', '0026_alter_dealer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='dealer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='capp.company'),
        ),
    ]
