# Generated by Django 4.2.2 on 2023-07-11 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0031_alter_dealer_dealer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='company',
        ),
    ]
