# Generated by Django 4.2.2 on 2023-07-11 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0007_company_company'),
        ('dapp', '0032_remove_dealer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='capp.company'),
        ),
    ]
