# Generated by Django 4.2.2 on 2023-07-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0034_alter_dealer_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='ph_no',
        ),
        migrations.AddField(
            model_name='dealer',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='phone_no',
            field=models.CharField(default='+977-', max_length=15),
        ),
    ]
