# Generated by Django 4.2.3 on 2023-07-15 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dapp', '0035_remove_dealer_company_remove_dealer_ph_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='dealer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealer',
            name='ph_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dealer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
