# Generated by Django 4.2.3 on 2023-07-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0039_alter_dealer_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='experience_years',
        ),
        migrations.AddField(
            model_name='dealer',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
