# Generated by Django 4.2.2 on 2023-06-29 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0001_initial'),
        ('fsapp', '0001_initial'),
        ('dapp', '0001_initial'),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='fieldstaff',
            name='company',
        ),
        migrations.RemoveField(
            model_name='fieldstaff',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='fieldstaff',
        ),
        migrations.AlterField(
            model_name='orders',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.dealer'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='fieldstaff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fsapp.fieldstaff'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapp.retailer'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Dealer',
        ),
        migrations.DeleteModel(
            name='FieldStaff',
        ),
        migrations.DeleteModel(
            name='Retailer',
        ),
    ]
