# Generated by Django 4.2.2 on 2023-07-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_product_category_remove_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
    ]
