# Generated by Django 4.2.2 on 2023-07-10 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='retailer',
        ),
    ]
