# Generated by Django 4.2.2 on 2023-07-10 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0011_retailer_retailer'),
        ('myapp', '0019_remove_orders_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rapp.retailer'),
        ),
    ]
