# Generated by Django 4.2.3 on 2023-07-15 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0036_remove_dealer_address_remove_dealer_nationality_and_more'),
        ('fsapp', '0014_alter_fieldstaff_city_alter_fieldstaff_company_and_more'),
        ('myapp', '0020_orders_retailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dapp.dealer'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='fieldstaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fsapp.fieldstaff'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
