# Generated by Django 4.2.3 on 2023-07-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_orderitem_order_alter_orders_dealer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='location_status',
            field=models.CharField(blank=True, choices=[('w', 'Warehouse'), ('s', 'In Store'), ('t', 'In Transit'), ('d', 'Delivered')], default='w', help_text='Product location status', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('o', 'Out of stock'), ('w', 'Way to deliver'), ('d', 'Delivered')], default='a', help_text='Product availability', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
