# Generated by Django 4.2.3 on 2023-07-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_category_review_rating_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='value',
            new_name='rating',
        ),
    ]
