# Generated by Django 4.2.3 on 2023-07-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('o', 'Out of stock'), ('w', 'Way to deliver'), ('d', 'Delivered'), ('c', 'Cancelled')], default='a', help_text='Product availability', max_length=1),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')]),
        ),
    ]
