# Generated by Django 4.2.3 on 2023-07-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_product_status_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'received'), ('c', 'cancelled'), ('w', 'Way to deliver')], default='w', help_text='order availability', max_length=1),
        ),
    ]
