# Generated by Django 4.2.3 on 2023-07-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_orders_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='total_amount',
            new_name='price',
        ),
    ]
