# Generated by Django 4.2.3 on 2023-07-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_rename_price_orderitem_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'received'), ('c', 'cancelled'), ('o', 'ordered')], default='o', help_text='order availability', max_length=1),
        ),
    ]
