# Generated by Django 4.2.3 on 2023-07-22 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_rename_total_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
