# Generated by Django 4.2.3 on 2023-07-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_amount',
        ),
    ]
