# Generated by Django 4.2.3 on 2023-07-23 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_orderitem_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
    ]
