# Generated by Django 4.2.3 on 2023-07-23 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_orderitem_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_amount',
        ),
    ]
