# Generated by Django 4.2.3 on 2023-07-25 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0015_remove_retailer_phone_no_retailer_phone_number'),
        ('myapp', '0043_remove_cart_price_loyaltypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltypoints',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rapp.retailer'),
        ),
    ]
