# Generated by Django 4.2.3 on 2023-07-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_loyaltypoints_retailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='retailer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='retailer',
        ),
    ]
