# Generated by Django 4.2.3 on 2023-07-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_rating_retailer_review_retailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
    ]
