# Generated by Django 4.2.3 on 2023-07-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_cart_retailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltypoints',
            name='retailer',
        ),
    ]
