# Generated by Django 4.2.3 on 2023-07-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_cartitem_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoyaltyPoints',
        ),
    ]
