# Generated by Django 4.2.3 on 2023-07-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_delete_loyaltypoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
    ]
