# Generated by Django 4.2.3 on 2023-07-26 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0017_retailer_loyalty_points'),
        ('myapp', '0056_remove_orders_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='loyalty_points',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rapp.retailer'),
        ),
    ]
