# Generated by Django 4.2.3 on 2023-07-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_orderitem_loyalty_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='loyalty_points',
        ),
    ]
