# Generated by Django 4.2.3 on 2023-07-27 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_remove_orderitem_loyalty_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='retailer',
        ),
    ]
