# Generated by Django 4.2.3 on 2023-07-27 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0061_alter_orderitem_retailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitem_retailer', to=settings.AUTH_USER_MODEL),
        ),
    ]
