# Generated by Django 4.2.3 on 2023-07-27 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_alter_orderitem_retailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='retailer',
        ),
    ]
