# Generated by Django 4.2.3 on 2023-07-27 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0018_remove_retailer_loyalty_points'),
        ('myapp', '0064_orderitem_retailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='rapp.retailer'),
        ),
    ]
