# Generated by Django 4.2.3 on 2023-07-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_alter_orderitem_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
