# Generated by Django 4.2.3 on 2023-07-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0066_orders_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location_status',
            field=models.CharField(blank=True, choices=[('w', 'Warehouse'), ('s', 'In Store'), ('t', 'In Transit'), ('d', 'Delivered')], default='s', help_text='Product location status', max_length=1),
        ),
    ]
