# Generated by Django 4.2.3 on 2023-07-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0067_alter_product_location_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_location',
            field=models.CharField(blank=True, choices=[('w', 'Warehouse'), ('s', 'In Store'), ('t', 'In Transit'), ('d', 'Delivered')], default='s', help_text='Product location status', max_length=1),
        ),
    ]
