# Generated by Django 4.2.3 on 2023-07-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0068_orders_order_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
