# Generated by Django 4.2.3 on 2023-07-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_orders_total_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='total_purchase',
        ),
    ]
