# Generated by Django 4.2.2 on 2023-07-05 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rapp', '0003_remove_retailer_name_retailer_retailer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='retailer',
        ),
        migrations.AddField(
            model_name='retailer',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
