# Generated by Django 4.2.2 on 2023-07-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0005_remove_retailer_name_retailer_retailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='retailer',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
