# Generated by Django 4.2.2 on 2023-07-06 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rapp', '0007_alter_retailer_company_alter_retailer_retailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='retailer',
        ),
        migrations.AlterField(
            model_name='retailer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
