# Generated by Django 4.2.2 on 2023-07-09 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rapp', '0009_retailer_retailer_alter_retailer_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='retailer',
        ),
        migrations.AlterField(
            model_name='retailer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
