# Generated by Django 4.2.3 on 2023-07-20 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0037_remove_dealer_ph_no_dealer_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fsapp', '0015_remove_fieldstaff_ph_no_fieldstaff_address_and_more'),
        ('rapp', '0012_alter_retailer_city_alter_retailer_dealer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='ph_no',
        ),
        migrations.AddField(
            model_name='retailer',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='phone_no',
            field=models.CharField(blank=True, default='+977-', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retailers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='dealer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retailers', to='dapp.dealer'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='fieldstaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fsapp.fieldstaff'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
