# Generated by Django 4.2.3 on 2023-07-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0013_remove_retailer_ph_no_retailer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='experience_years',
        ),
    ]
