# Generated by Django 4.2.3 on 2023-07-25 05:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0014_remove_retailer_experience_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='retailer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
