# Generated by Django 4.2.3 on 2023-07-26 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dapp', '0039_alter_dealer_company'),
        ('rapp', '0015_remove_retailer_phone_no_retailer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_retailer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='dealer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dealer_retailer', to='dapp.dealer'),
        ),
    ]
