# Generated by Django 4.2.3 on 2023-07-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0016_alter_retailer_company_alter_retailer_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
    ]
