# Generated by Django 4.2.3 on 2023-07-27 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0017_retailer_loyalty_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='loyalty_points',
        ),
    ]
