# Generated by Django 4.2.3 on 2023-07-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0018_remove_retailer_loyalty_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
