# Generated by Django 4.2.3 on 2023-07-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0019_retailer_first_name_retailer_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
    ]
