# Generated by Django 4.2.2 on 2023-07-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0003_alter_company_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ph_no',
            field=models.CharField(max_length=10),
        ),
    ]
