# Generated by Django 4.2.2 on 2023-07-11 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0005_alter_company_company_alter_company_ph_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company',
        ),
    ]
