# Generated by Django 4.2.2 on 2023-07-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0008_remove_company_city_remove_company_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Phone_No',
            field=models.CharField(default='+977 ', max_length=15),
        ),
    ]
