# Generated by Django 4.2.2 on 2023-07-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0010_alter_company_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='City',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='Nationality',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='State',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='Zipcode',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
