# Generated by Django 4.2.2 on 2023-07-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0011_alter_company_city_alter_company_nationality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='City',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Email_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Nationality',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Phone_No',
        ),
        migrations.RemoveField(
            model_name='company',
            name='State',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Zipcode',
        ),
        migrations.AddField(
            model_name='company',
            name='ph_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email_id',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
