# Generated by Django 4.2.3 on 2023-07-25 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0017_company_email_id_company_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='phone_no',
        ),
    ]
