# Generated by Django 4.2.3 on 2023-07-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0019_company_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_staff',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
