# Generated by Django 4.2.3 on 2023-07-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0020_company_is_active_company_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='is_staff',
            new_name='staff_status',
        ),
    ]
