# Generated by Django 4.2.3 on 2023-07-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0021_rename_is_staff_company_staff_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='company',
            name='staff_status',
        ),
    ]
