# Generated by Django 4.2.3 on 2023-07-28 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capp', '0022_remove_company_is_active_remove_company_staff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
